---
- hosts: all
  remote_user: ec2-user
  become: True
  vars_files:
    - vars.yml
    - ~/.ansibleawscreds
    - ~/.ansiblerhsmcreds
  vars:
    ansible_ssh_private_key_file: ~/.ssh/{{ ssh_key }}
  roles:
   - { role: install, tags: ["install"] }
  
